CREATE TABLE MN_DB_DIFF_SNAPSHOTS
  (
    SNAPSHOT_NAME      VARCHAR2(50) PRIMARY KEY,
    SNAPSHOT_COMMENT   VARCHAR2(255),
    SNAPSHOT_TIME      DATE,
    DIFF_SNAPSHOT_TIME DATE,
    DIFF_REPORT CLOB
  )
  ENABLE PRIMARY KEY USING INDEX TABLESPACE MN_IDX1;
CREATE TABLE MN_DB_DIFF_USER_TABLES
  (
    TABLE_NAME        VARCHAR2(40),
    TABLESPACE_NAME   VARCHAR2(30),
    IOT_NAME          VARCHAR2(30),
    PARTITIONED       VARCHAR2(3),
    TEMPORARY         VARCHAR2(1),
    SNAPSHOT_TIME     DATE,
    ROWCOUNT          NUMBER(20),
    NEW_FLAG          VARCHAR2(1),
    DELETED_FLAG      VARCHAR2(1),
    ROWCNT_DIFF_FLAG  VARCHAR2(1),
    COLS_CHANGED_FLAG VARCHAR2(1),
    CHANGED_FLAG      VARCHAR2(1),
    CHANGE_LOG        VARCHAR2(2000)
  );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_TABLES_U1 ON MN_DB_DIFF_USER_TABLES
  (
    TABLE_NAME, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_TAB_COLUMNS
    (
      TABLE_NAME     VARCHAR2(30),
      COLUMN_NAME    VARCHAR2(30),
      DATA_TYPE      VARCHAR2(106),
      DATA_LENGTH    NUMBER,
      DATA_PRECISION NUMBER,
      DATA_SCALE     NUMBER,
      NULLABLE       VARCHAR2(1),
      COLUMN_ID      NUMBER,
      DEFAULT_LENGTH NUMBER,
      DATA_DEFAULT   VARCHAR2(2000),
      SNAPSHOT_TIME  DATE,
      NEW_FLAG       VARCHAR2(1),
      DELETED_FLAG   VARCHAR2(1),
      CHANGED_FLAG   VARCHAR2(1),
      CHANGE_LOG     VARCHAR2(2000)
    );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_TAB_COLUMNS_U1 ON MN_DB_DIFF_USER_TAB_COLUMNS
  (
    TABLE_NAME, COLUMN_NAME, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_INDEXES
    (
      INDEX_NAME      VARCHAR2(35),
      INDEX_TYPE      VARCHAR2(27),
      TABLE_NAME      VARCHAR2(30),
      UNIQUENESS      VARCHAR2(9),
      TABLESPACE_NAME VARCHAR2(30),
      STATUS          VARCHAR2(8),
      PARTITIONED     VARCHAR2(3),
      COLUMN_LIST     VARCHAR2(2000),
      SNAPSHOT_TIME   DATE,
      NEW_FLAG        VARCHAR2(1),
      DELETED_FLAG    VARCHAR2(1),
      CHANGED_FLAG    VARCHAR2(1),
      CHANGE_LOG      VARCHAR2(2000)
    );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_INDEXES_U1 ON MN_DB_DIFF_USER_INDEXES
  (
    INDEX_NAME, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE INDEX MN_DB_DIFF_USER_INDEXES_N1 ON MN_DB_DIFF_USER_INDEXES
    (
      TABLE_NAME,
      SNAPSHOT_TIME
    )
    TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_IND_COLUMNS
    (
      INDEX_NAME      VARCHAR2(30),
      COLUMN_NAME     VARCHAR2(4000),
      COLUMN_POSITION NUMBER,
      SNAPSHOT_TIME   DATE
    );
  CREATE INDEX MN_DB_DIFF_USER_IND_COLUMNS_N1 ON MN_DB_DIFF_USER_IND_COLUMNS
    (
      INDEX_NAME,
      SNAPSHOT_TIME
    )
    TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_VIEWS
    (
      VIEW_NAME VARCHAR2(30),
      TEXT CLOB,
      STATUS        VARCHAR2(8),
      NEW_FLAG      VARCHAR2(1),
      DELETED_FLAG  VARCHAR2(1),
      CHANGED_FLAG  VARCHAR2(1),
      SNAPSHOT_TIME DATE,
      CHANGE_LOG    VARCHAR2(2000)
    );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_VIEWS_U1 ON MN_DB_DIFF_USER_VIEWS
  (
    VIEW_NAME, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_CONSTRAINTS
    (
      CONSTRAINT_NAME  VARCHAR2(35),
      CONSTRAINT_TYPE  VARCHAR2(1),
      TABLE_NAME       VARCHAR2(30),
      SEARCH_CONDITION VARCHAR2(2000),
      COLUMN_LIST      VARCHAR2(2000),
      STATUS           VARCHAR2(8),
      INVALID          VARCHAR2(7),
      NEW_FLAG         VARCHAR2(1),
      DELETED_FLAG     VARCHAR2(1),
      CHANGED_FLAG     VARCHAR2(1),
      SNAPSHOT_TIME    DATE,
      CHANGE_LOG       VARCHAR2(2000)
    );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_CONSTRAINTS_U1 ON MN_DB_DIFF_USER_CONSTRAINTS
  (
    CONSTRAINT_NAME, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE INDEX MN_DB_DIFF_USER_CONSTRAINTS_N1 ON MN_DB_DIFF_USER_CONSTRAINTS
    (
      TABLE_NAME,
      SNAPSHOT_TIME
    )
    TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_SEQUENCES
    (
      SEQUENCE_NAME VARCHAR2(30),
      MIN_VALUE     NUMBER,
      MAX_VALUE     NUMBER,
      INCREMENT_BY  NUMBER,
      CACHE_SIZE    NUMBER,
      NEW_FLAG      VARCHAR2(1),
      DELETED_FLAG  VARCHAR2(1),
      CHANGED_FLAG  VARCHAR2(1),
      SNAPSHOT_TIME DATE,
      CHANGE_LOG    VARCHAR2(2000)
    );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_SEQUENCES_U1 ON MN_DB_DIFF_USER_SEQUENCES
  (
    SEQUENCE_NAME, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_USER_OBJECTS
    (
      OBJECT_NAME   VARCHAR2(128),
      OBJECT_TYPE   VARCHAR2(30),
      STATUS        VARCHAR2(30),
      SNAPSHOT_TIME DATE
    );
CREATE UNIQUE INDEX MN_DB_DIFF_USER_OBJECTS_U1 ON MN_DB_DIFF_USER_OBJECTS
  (
    OBJECT_NAME, OBJECT_TYPE, SNAPSHOT_TIME
  )
  TABLESPACE MN_IDX1;
  CREATE TABLE MN_DB_DIFF_DATA
    (
      table_id         NUMBER(20, 0),
      table_name       VARCHAR2(30),
      src_records      NUMBER(20),
      tgt_records      NUMBER(20),
      src_diff_records NUMBER(20),
      tgt_diff_records NUMBER(20),
      diff_cols_flag   VARCHAR2(1),
      sql_text CLOB,
      diff_sql_text CLOB,
      log_text CLOB,
      date_created TIMESTAMP
    ) ;
  CREATE TABLE MN_DB_DIFF_IGNORE_COLS
    (
      table_name  VARCHAR2(30),
      column_name VARCHAR2(30)
    );
    CREATE TABLE MN_DB_DIFF_IGNORE_TABS
    ( table_name VARCHAR2(30)
    );
  BEGIN
    DELETE FROM MN_DB_DIFF_IGNORE_COLS ;
    INSERT
    INTO MN_DB_DIFF_IGNORE_COLS
      (
        table_name,
        column_name
      )
      VALUES
      (
        '',
        'DATE_CREATED'
      );
    INSERT
    INTO MN_DB_DIFF_IGNORE_COLS
      (
        table_name,
        column_name
      )
      VALUES
      (
        '',
        'DATE_UPDATED'
      );
    COMMIT;
  END;
